import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Header } from "@/components/Header";
import { AppContext, AppProvider } from "@/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "JABYA",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-slate-300 p-6`}>
				<AppProvider>
				<Header/>
				{children}
				</AppProvider>
			</body>
		</html>
	);
}
